export const portfolioData = {
  portfolios: [
    {
      id: 1,
      title: "Aashka & Shanil",
      category: "Wedding",
      image: "https://res.cloudinary.com/dtrrsp1ll/image/upload/v1750501584/_J7A8868_da7lor.jpg",
      slug: "romantic-garden-wedding",
      weddingDate: "March 15, 2024",
      location: "Fairmont & Raffles, Jaipur",
      couple: "Aashka & Shanil",
      description:
        "A spectacular celebration of love, tradition, and elegance at Fairmont & Raffles Jaipur. Set against the backdrop of Jaipur's royal heritage, their three-day celebration was filled with vibrant colors, heartfelt emotions, and unforgettable moments.",
      story:
        "Aashka and Shanil's love story began in college, where a chance encounter in the library led to countless conversations and shared dreams. Eight years later, surrounded by family and friends, they celebrated their union in the most magnificent way. The wedding perfectly blended traditional Rajasthani customs with contemporary elegance, creating a visual feast that will be remembered for generations.",
      details: {
        venue: "Fairmont & Raffles Jaipur",
        date: "March 15, 2024",
        guests: "300+ Guests",
        duration: "3 Days",
      },
      images: [
        "https://res.cloudinary.com/dtrrsp1ll/image/upload/v1750501584/_J7A8868_da7lor.jpg",
        "https://res.cloudinary.com/dtrrsp1ll/image/upload/v1750501538/VS1_63_yftdsi.jpg",
        "https://res.cloudinary.com/dtrrsp1ll/image/upload/v1750501499/_J7A3450_sfixoc.jpg",
        "https://res.cloudinary.com/dtrrsp1ll/image/upload/v1750501110/_A2A8144_dfhitk.jpg",
        "https://res.cloudinary.com/dtrrsp1ll/image/upload/v1750501565/_A2A0821_lu9mj8.jpg",
        "https://res.cloudinary.com/dtrrsp1ll/image/upload/v1750501572/_A2A9751_kwyltf.jpg",
        "https://res.cloudinary.com/dtrrsp1ll/image/upload/v1750501540/VS1_66_rf2nxp.jpg",
        "https://res.cloudinary.com/dtrrsp1ll/image/upload/v1750501472/_A2A6442_m9ufby.jpg",
        "https://res.cloudinary.com/dtrrsp1ll/image/upload/v1750501474/_A2A6313_ghjcfj.jpg",
        "https://res.cloudinary.com/dtrrsp1ll/image/upload/v1750501541/VS1_68_rvpn6k.jpg",
      ],
    },
    {
      id: 2,
      title: "Priya & Arjun",
      category: "Wedding",
      image: "https://res.cloudinary.com/dtrrsp1ll/image/upload/v1750501538/VS1_63_yftdsi.jpg",
      slug: "vineyard-celebration",
      weddingDate: "February 20, 2024",
      location: "Sula Vineyards, Nashik",
      couple: "Priya & Arjun",
      description:
        "Priya and Arjun chose the picturesque Sula Vineyards in Nashik for their intimate wedding celebration. Surrounded by rolling hills and endless vineyards, their wedding was a perfect blend of rustic charm and sophisticated elegance.",
      story:
        "Wine enthusiasts from the start, Priya and Arjun's first date was at a wine tasting event. It was only fitting that they would celebrate their union at one of India's most beautiful vineyards. Their wedding was an intimate affair, focusing on meaningful connections and creating lasting memories with their closest family and friends.",
      details: {
        venue: "Sula Vineyards, Nashik",
        date: "February 20, 2024",
        guests: "150+ Guests",
        duration: "2 Days",
      },
      images: [
        "https://res.cloudinary.com/dtrrsp1ll/image/upload/v1750501538/VS1_63_yftdsi.jpg",
        "https://res.cloudinary.com/dtrrsp1ll/image/upload/v1750501584/_J7A8868_da7lor.jpg",
        "https://res.cloudinary.com/dtrrsp1ll/image/upload/v1750501499/_J7A3450_sfixoc.jpg",
        "https://res.cloudinary.com/dtrrsp1ll/image/upload/v1750501540/VS1_66_rf2nxp.jpg",
        "https://res.cloudinary.com/dtrrsp1ll/image/upload/v1750501541/VS1_68_rvpn6k.jpg",
        "https://res.cloudinary.com/dtrrsp1ll/image/upload/v1750501542/VS1_72_uzlbd0.jpg",
        "https://res.cloudinary.com/dtrrsp1ll/image/upload/v1750501543/VS1_74_tfejme.jpg",
        "https://res.cloudinary.com/dtrrsp1ll/image/upload/v1750501544/VS1_78_es7hss.jpg",
      ],
    },
    {
      id: 3,
      title: "Riya & Vikram",
      category: "Wedding",
      image: "https://res.cloudinary.com/dtrrsp1ll/image/upload/v1750501565/_A2A0821_lu9mj8.jpg",
      slug: "royal-palace-wedding",
      weddingDate: "January 10, 2024",
      location: "Udaipur Palace",
      couple: "Riya & Vikram",
      description:
        "A royal wedding celebration at the magnificent palaces of Udaipur, where tradition meets luxury in the most spectacular way.",
      story:
        "Riya and Vikram's wedding was a grand celebration of love and tradition, set against the stunning backdrop of Udaipur's royal palaces. Every detail was carefully planned to create a truly magical experience.",
      details: {
        venue: "Udaipur Palace",
        date: "January 10, 2024",
        guests: "400+ Guests",
        duration: "3 Days",
      },
      images: [
        "https://res.cloudinary.com/dtrrsp1ll/image/upload/v1750501565/_A2A0821_lu9mj8.jpg",
        "https://res.cloudinary.com/dtrrsp1ll/image/upload/v1750501572/_A2A9751_kwyltf.jpg",
        "https://res.cloudinary.com/dtrrsp1ll/image/upload/v1750501110/_A2A8144_dfhitk.jpg",
        "https://res.cloudinary.com/dtrrsp1ll/image/upload/v1750501109/_A2A6598_byfyow.jpg",
        "https://res.cloudinary.com/dtrrsp1ll/image/upload/v1750501109/_A2A6694_xhvb9x.jpg",
        "https://res.cloudinary.com/dtrrsp1ll/image/upload/v1750501109/_A2A7040_k5jcq6.jpg",
        "https://res.cloudinary.com/dtrrsp1ll/image/upload/v1750501110/_A2A7439_lchfpb.jpg",
      ],
    },
  ],
}
